version: '3'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www
    depends_on:
      - database
    networks:
      - mirspay
  nginx:
    image: nginx:latest
    depends_on:
      - app
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    networks:
      - mirspay
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8.0'
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - mirspay
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  mirspay:
    driver: bridge
