# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Mirspay\:
        resource: '../src/Mirspay'
        exclude:
            - '../src/Mirspay/DependencyInjection/'
            - '../src/Mirspay/Entity/'
            - '../src/Mirspay/Kernel.php'
    Custom\:
        resource: '../src/Custom'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Mirspay\Payment\LiqPay\Gateway:
        arguments:
            $publicKey: '%env(LIQPAY_PUBLIC_KEY)%'
            $privateKey: '%env(LIQPAY_PRIVATE_KEY)%'
            $serverCallbackHandler: '@Mirspay\Payment\LiqPay\ServerCallbackHandler'
        tags: ['app.payment.gateway']

    Mirspay\Payment\LiqPay\Signature:
        arguments:
            $privateKey: '%env(LIQPAY_PRIVATE_KEY)%'

    Mirspay\Order\OrderTotalAmountCalculator:
        arguments:
            $currencyCode: 'UAH'

    Mirspay\Subscriber\Channel\HttpNotificationChannel:
        tags:
            - { name: 'app.subscriber.channel', type: 'http' }

    Mirspay\Subscriber\Channel\SimpleArrayChannelMessage:
        tags:
            - { name: 'app.subscriber.message', type: 'simple' }
